### ISSUE TITLE
Implement to deploy the number of Replicaset by Plugin ID

### ISSUE THREAD

**Issue by jihyungSong** [cloudforet-io/supervisor#1]
Currently, Supervisor is implemented to set the number of replicas according to the value in Config, but it does not work properly.

```yaml
KubernetesConnector:
    namespace: supervisor
    start_port: 50051
    end_port: 50052
    headless: true
    replica:
        inventory.Collector: 1
        inventory.Collector?aws-ec2: 2
        inventory.Collector?aws-cloud-services: 2
    nodeSelector:
        Category: supervisor
```

It is needed to modify to deploy for each combination of `service_type` and `plugin_id` of the replica item.
