### ISSUE TITLE
Add settings to Supervisor service

### ISSUE THREAD

**Issue by whdalsrnt** [cloudforet-io/supervisor#8]
Additional configuration is required for the on-premise environment.
- `imagePullSecrets`: Used to download images from private image registry
- `env`: Used to set env such as `HTTP_PROXY` and `HTTPS_PROXY`

[Configuration]
```
application_scheduler:
    ...
    CONNECTORS:
        ...
        KubernetesConnector:
            ...
            imagePullSecrets:
            - name: <private_registry_secrets>
            env:
            - name: HTTP_PROXY
               value: <proxy_url>
            - name: HTTPS_PROXY
               value: <proxy_url>
```
